title: Christian Ponte
email: christian.ponte@udc.es
description: >- # this means to ignore newlines until "baseurl:"
  I'm a PhD student at Universidade da Coruña, under the direction of Dr. María J. Martín Santamaría and Dr. Jorge González Domínguez.
baseurl: ""
url: "https://chponte.github.io/"

socials:
  - title: Email
    icon: fas fa-envelope
    url: mailto:christian.ponte@udc.es
  - title: Twitter
    icon: fab fa-twitter
    url: https://twitter.com/chpont3
  - title: Github
    icon: fab fa-github
    url: https://github.com/chponte
  - title: ORCID
    icon: fab fa-orcid
    url: https://orcid.org/0000-0002-4728-6398
  - title: ResearchGate
    icon: fab fa-researchgate
    url: https://www.researchgate.net/profile/Christian_Ponte-Fernandez

# Build settings
plugins:
  - jekyll-analytics

collections:
  publications:
    output: true

jekyll_analytics:
  GoogleAnalytics:
    id: UA-129572314-1
    anonymizeIp: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
